# Generated by Django 3.1 on 2021-04-22 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentMixin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlaceMixin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PlaceToEat',
            fields=[
                ('placemixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='facilities.placemixin')),
            ],
            bases=('facilities.placemixin',),
        ),
        migrations.CreateModel(
            name='PlaceToStay',
            fields=[
                ('placemixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='facilities.placemixin')),
            ],
            bases=('facilities.placemixin',),
        ),
        migrations.CreateModel(
            name='PlaceToVisit',
            fields=[
                ('placemixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='facilities.placemixin')),
            ],
            bases=('facilities.placemixin',),
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('slug', models.SlugField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('eat', models.ManyToManyField(blank=True, related_name='eats', to='facilities.PlaceToEat')),
                ('hostel', models.ManyToManyField(blank=True, related_name='hostels', to='facilities.PlaceToStay')),
                ('place', models.ManyToManyField(blank=True, related_name='places', to='facilities.PlaceToVisit')),
            ],
        ),
        migrations.CreateModel(
            name='RatingToVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_to_visit', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_to_visit', to='facilities.placetovisit')),
            ],
        ),
        migrations.CreateModel(
            name='RatingToStay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_to_stay', to=settings.AUTH_USER_MODEL)),
                ('stay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_to_stay', to='facilities.placetostay')),
            ],
        ),
        migrations.CreateModel(
            name='RatingToEat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_to_eat', to=settings.AUTH_USER_MODEL)),
                ('eat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_to_eat', to='facilities.placetoeat')),
            ],
        ),
        migrations.CreateModel(
            name='LikeToVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_to_visit', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_to_visit', to='facilities.placetovisit')),
            ],
        ),
        migrations.CreateModel(
            name='LikeToStay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_to_stay', to=settings.AUTH_USER_MODEL)),
                ('stay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_to_stay', to='facilities.placetostay')),
            ],
        ),
        migrations.CreateModel(
            name='LikeToEat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_to_eat', to=settings.AUTH_USER_MODEL)),
                ('eat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_to_eat', to='facilities.placetoeat')),
            ],
        ),
        migrations.CreateModel(
            name='ImageToVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='visit')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_to_visit', to='facilities.placetovisit')),
            ],
        ),
        migrations.CreateModel(
            name='ImageToStay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='stay')),
                ('stay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_to_stay', to='facilities.placetostay')),
            ],
        ),
        migrations.CreateModel(
            name='ImageToEat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='eat')),
                ('eat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_to_eat', to='facilities.placetoeat')),
            ],
        ),
        migrations.CreateModel(
            name='CommentToVisit',
            fields=[
                ('commentmixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='facilities.commentmixin')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='comments_to_visit', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_to_visit', to='facilities.placetovisit')),
            ],
            bases=('facilities.commentmixin',),
        ),
        migrations.CreateModel(
            name='CommentToStay',
            fields=[
                ('commentmixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='facilities.commentmixin')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='comments_to_stay', to=settings.AUTH_USER_MODEL)),
                ('stay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_to_stay', to='facilities.placetostay')),
            ],
            bases=('facilities.commentmixin',),
        ),
        migrations.CreateModel(
            name='CommentToEat',
            fields=[
                ('commentmixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='facilities.commentmixin')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='comments_to_eat', to=settings.AUTH_USER_MODEL)),
                ('eat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_to_eat', to='facilities.placetoeat')),
            ],
            bases=('facilities.commentmixin',),
        ),
    ]
